B"H

# Milestone 2: Cleaning and Formatting the Flat File Source

- DSC-540
- David Koyrakh
- Professor Catie Williams

## Load and examine the data

In [1]:
# Import necessary libraries
import pandas as pd

In [2]:
# Load the raw USDA Economic Research Service dataset
dataset = pd.read_csv("USDA_dataset.csv")

# Display head
print(dataset.head(100))

# Display the dimensions of the dataset
print("Dataset dimensions:", dataset.shape)

    FIPS_Code State      Area_Name                  Attribute        Value
0           0    US  United States  Civilian_labor_force_2000  142601576.0
1           0    US  United States              Employed_2000  136904853.0
2           0    US  United States            Unemployed_2000    5696723.0
3           0    US  United States     Unemployment_rate_2000          4.0
4           0    US  United States  Civilian_labor_force_2001  143786537.0
..        ...   ...            ...                        ...          ...
95       1000    AL        Alabama            Unemployed_2000      99442.0
96       1000    AL        Alabama     Unemployment_rate_2000          4.6
97       1000    AL        Alabama  Civilian_labor_force_2001    2128027.0
98       1000    AL        Alabama              Employed_2001    2017467.0
99       1000    AL        Alabama            Unemployed_2001     110560.0

[100 rows x 5 columns]
Dataset dimensions: (316633, 5)

By observing the dataset head and checking the file manually, it appears that the first ~100 rows are overall statistics on the whole United States, followed by over 316,500 rows with statistics on specific counties. This is organized by state, in alphabetic order.

### Ensure that all states are represented

In [3]:
# Count unique values for the columns: State, Area_Name, and Attribute
print("Count of unique 'State' values:", dataset['State'].nunique())
print("Count of unique 'Area_Name' values:", dataset['Area_Name'].nunique())
print("Count of unique 'Attribute' values:", dataset['Attribute'].nunique())

Count of unique 'State' values: 53
Count of unique 'Area_Name' values: 3276
Count of unique 'Attribute' values: 97

In [4]:
print("All unique 'State' values:\n", dataset['State'].unique())

All unique 'State' values:
 ['US' 'AL' 'AK' 'AZ' 'AR' 'CA' 'CO' 'CT' 'DE' 'DC' 'FL' 'GA' 'HI' 'ID'
 'IL' 'IN' 'IA' 'KS' 'KY' 'LA' 'ME' 'MD' 'MA' 'MI' 'MN' 'MS' 'MO' 'MT'
 'NE' 'NV' 'NH' 'NJ' 'NM' 'NY' 'NC' 'ND' 'OH' 'OK' 'OR' 'PA' 'RI' 'SC'
 'SD' 'TN' 'TX' 'UT' 'VT' 'VA' 'WA' 'WV' 'WI' 'WY' 'PR']

The dataset includes:
- 50 states (AL through WY)
- 1 federal district (DC)
- 1 territory (PR)
- 1 national aggregate (US)

This explains why there are 3 additional "State" variables above the expected count of 50 states.

## Step 1: Drop county-level data

Since this project is state-focused, data for each specific county is out of scope.

Thankfully, the dataset already comes with aggregate data for each state, so we will extract those out by removing county-specific data.

We will keep US/country-wide aggregate data, for potential use as a baseline for future comparisons. We will also keep DC and Puerto Rico (PR), for now.

### Check for county identifiers

In [5]:
# Display the first 150 rows excluding rows where State is 'US'
dataset_filtered = dataset[dataset['State'] != 'US']
print(dataset_filtered.head(150))

     FIPS_Code State           Area_Name                  Attribute      Value
93        1000    AL             Alabama  Civilian_labor_force_2000  2147173.0
94        1000    AL             Alabama              Employed_2000  2047731.0
95        1000    AL             Alabama            Unemployed_2000    99442.0
96        1000    AL             Alabama     Unemployment_rate_2000        4.6
97        1000    AL             Alabama  Civilian_labor_force_2001  2128027.0
..         ...   ...                 ...                        ...        ...
238       1001    AL  Autauga County, AL  Civilian_labor_force_2012    25762.0
239       1001    AL  Autauga County, AL              Employed_2012    23932.0
240       1001    AL  Autauga County, AL            Unemployed_2012     1830.0
241       1001    AL  Autauga County, AL     Unemployment_rate_2012        7.1
242       1001    AL  Autauga County, AL  Civilian_labor_force_2013    25783.0

[150 rows x 5 columns]

Based on the above, county-specific rows are unique in that they contain commas in the `Area_Name` column. Therefore, we can filter them out by targeting rows which match that criteria.

### Remove county-level rows from the dataset

In [6]:
# Count data before filtering
print("Count of unique 'Area_Name' values BEFORE filtering county-level data:", dataset['Area_Name'].nunique())

# Filter out the county-level data, using presence of a comma in the 'Area_Name' column as a marker
dataset = dataset[~dataset['Area_Name'].str.contains(',')]

# Re-count unique values
print("Count of unique `Area_Name` values AFTER filtering county-level data:", dataset['Area_Name'].nunique())

Count of unique 'Area_Name' values BEFORE filtering county-level data: 3276
Count of unique `Area_Name` values AFTER filtering county-level data: 53

In [7]:
# Display the first 150 rows excluding rows where State is 'US'
dataset_filtered = dataset[dataset['State'] != 'US']
print(dataset_filtered.head(150))

      FIPS_Code State Area_Name                  Attribute      Value
93         1000    AL   Alabama  Civilian_labor_force_2000  2147173.0
94         1000    AL   Alabama              Employed_2000  2047731.0
95         1000    AL   Alabama            Unemployed_2000    99442.0
96         1000    AL   Alabama     Unemployment_rate_2000        4.6
97         1000    AL   Alabama  Civilian_labor_force_2001  2128027.0
...         ...   ...       ...                        ...        ...
6737       2000    AK    Alaska     Unemployment_rate_2012        7.2
6738       2000    AK    Alaska  Civilian_labor_force_2013   363544.0
6739       2000    AK    Alaska              Employed_2013   338104.0
6740       2000    AK    Alaska            Unemployed_2013    25440.0
6741       2000    AK    Alaska     Unemployment_rate_2013        7.0

[150 rows x 5 columns]

All of the rows containing county-specific data have been removed.

## Step 2: Drop unnecessary columns

In [8]:
# List all column names in the dataset
print(dataset.columns)

Index(['FIPS_Code', 'State', 'Area_Name', 'Attribute', 'Value'], dtype='object')

We don't need the `FIPS_Code` column, so let's drop it.

In [9]:
dataset = dataset.drop(columns=['FIPS_Code'])
print(dataset.columns)

Index(['State', 'Area_Name', 'Attribute', 'Value'], dtype='object')

## Step 3: Make `Attribute` values more readable

The 'Attribute' column contains categorical names for sets of important data points, but isn't very readable. In this step, I will perform the following transformations to make the values more human-readable:
- Replace underscores with spaces
- Wrap the year in parentheses

In [10]:
import re

# Function to reformat Attribute names
def format_attribute(attribute):
    # Replace underscores with spaces
    attribute = attribute.replace("_", " ")
    # Move the year (if present) to parentheses at the end
    attribute = re.sub(r'(\d{4})$', r'(\1)', attribute)
    return attribute

# Apply formatting to the 'Attribute' column
dataset['Attribute'] = dataset['Attribute'].apply(format_attribute)

# Display the transformed dataset
dataset.head()

  State      Area_Name                    Attribute        Value
0    US  United States  Civilian labor force (2000)  142601576.0
1    US  United States              Employed (2000)  136904853.0
2    US  United States            Unemployed (2000)    5696723.0
3    US  United States     Unemployment rate (2000)          4.0
4    US  United States  Civilian labor force (2001)  143786537.0

The `Attribute` values are now more human-readable.

## Step 4: Handle duplicate entries

In order to pivot the dataset in the following step, we have to make sure that there are no duplicate entries for 'State', 'Area_Name', and 'Attribute' combinations. We will first check if there are, and if found, handle them accordingly.

In [11]:
# Identify rows that have duplicates for the combination (State, Area_Name, Attribute)
dupes_mask = dataset.duplicated(subset=['State', 'Area_Name', 'Attribute'], keep=False)

# Display results
if dupes_mask.any():
    print("Duplicates found:")
    print(dataset[dupes_mask].sort_values(['State', 'Area_Name', 'Attribute']))
else:
    print("No duplicates found.")

Duplicates found:
      State             Area_Name                    Attribute     Value
31727    DC  District of Columbia  Civilian labor force (2000)  309977.0
31824    DC  District of Columbia  Civilian labor force (2000)  309977.0
31731    DC  District of Columbia  Civilian labor force (2001)  311232.0
31828    DC  District of Columbia  Civilian labor force (2001)  311232.0
31735    DC  District of Columbia  Civilian labor force (2002)  308760.0
...     ...                   ...                          ...       ...
31907    DC  District of Columbia     Unemployment rate (2020)       7.9
31814    DC  District of Columbia     Unemployment rate (2021)       6.8
31911    DC  District of Columbia     Unemployment rate (2021)       6.8
31818    DC  District of Columbia     Unemployment rate (2022)       4.7
31915    DC  District of Columbia     Unemployment rate (2022)       4.7

[188 rows x 4 columns]

There are duplicates! Let's check if each duplicate has the same Value:

In [12]:
dupes = dataset[dataset.duplicated(subset=['State', 'Area_Name', 'Attribute'], keep=False)]

# Group duplicates, and count how many unique Value entires each group has
unique_value_counts = dupes.groupby(['State', 'Area_Name', 'Attribute'])['Value'].nunique()

# Identify which groups have more than 1 unique Value
duplicates_with_different_values = unique_value_counts[unique_value_counts > 1]
duplicates_with_different_values

Series([], Name: Value, dtype: int64)

All of the duplicates are identical, so duplicates can be easily dropped.

In [13]:
# Drop the duplicates
dataset = dataset.drop_duplicates(subset=['State', 'Area_Name', 'Attribute'])

## Step 5: Pivot attributes into columns (long to wide format transformation)

Currently, this dataset contains a large number of rows for each state, since each state has its own row for each individual `Attribute` field. The data will be much more readable if this row redundancy is reduced, by pivoting the `Attribute` fields into individual columns. This will result in a cleaner dataset - one state per row - and it will be more straightforward to read and process in the future.

In [14]:
dataset_pivoted = dataset.pivot(
    index=['State', 'Area_Name'], 
    columns='Attribute', 
    values='Value'
)
dataset_pivoted.reset_index(inplace=True)
dataset_pivoted

Attribute,State,Area_Name,Civilian labor force (2000),Civilian labor force (2001),Civilian labor force (2002),Civilian labor force (2003),Civilian labor force (2004),Civilian labor force (2005),Civilian labor force (2006),Civilian labor force (2007),...,Unemployment rate (2014),Unemployment rate (2015),Unemployment rate (2016),Unemployment rate (2017),Unemployment rate (2018),Unemployment rate (2019),Unemployment rate (2020),Unemployment rate (2021),Unemployment rate (2022),Urban Influence Code (2013)
0,AK,Alaska,319777.0,321652.0,327054.0,332494.0,337469.0,344157.0,348756.0,350233.0,...,6.7,6.3,6.6,6.5,6.0,5.6,8.3,6.4,4.0,NaN
1,AL,Alabama,2147173.0,2128027.0,2112621.0,2128668.0,2138306.0,2140356.0,2170007.0,2180448.0,...,6.7,6.1,5.9,4.5,3.9,3.2,6.4,3.4,2.6,NaN
2,AR,Arkansas,1260507.0,1261419.0,1276964.0,1282578.0,1302378.0,1333880.0,1346532.0,1350811.0,...,5.9,5.0,4.0,3.7,3.7,3.5,6.2,4.1,3.3,NaN
3,AZ,Arizona,2510611.0,2593664.0,2683502.0,2728649.0,2788618.0,2862517.0,2970679.0,3018805.0,...,6.8,6.1,5.5,5.0,4.8,4.8,7.8,5.1,3.8,NaN
4,CA,California,16837536.0,17096428.0,17246528.0,17271899.0,17374506.0,17537931.0,17661179.0,17910726.0,...,7.6,6.3,5.5,4.8,4.2,4.1,10.1,7.3,4.2,NaN
5,CO,Colorado,2358371.0,2396012.0,2448903.0,2490397.0,2539389.0,2572382.0,2640452.0,2687742.0,...,5.0,3.7,3.1,2.6,3.0,2.7,6.8,5.4,3.0,NaN
6,CT,Connecticut,1760697.0,1749195.0,1776064.0,1785737.0,1777510.0,1794301.0,1831083.0,1856008.0,...,6.6,5.6,4.8,4.4,3.9,3.6,7.9,6.3,4.2,NaN
7,DC,District of Columbia,309977.0,311232.0,308760.0,308454.0,313735.0,318130.0,320581.0,326557.0,...,7.7,6.9,6.2,6.1,5.7,5.5,7.9,6.8,4.7,1.0
8,DE,Delaware,412956.0,421563.0,417207.0,415890.0,421093.0,433375.0,443228.0,445306.0,...,5.6,4.8,4.5,4.5,3.7,3.6,7.5,5.5,4.5,NaN
9,FL,Florida,7917857.0,8048882.0,8050051.0,8123135.0,8347316.0,8647279.0,8927098.0,9113604.0,...,6.4,5.5,4.9,4.3,3.6,3.2,8.1,4.6,2.9,NaN
10,GA,Georgia,4202695.0,4257901.0,4341617.0,4414282.0,4464780.0,4598159.0,4713863.0,4810264.0,...,7.1,6.1,5.4,4.8,4.0,3.6,6.5,3.9,3.0,NaN
11,HI,Hawaii,605395.0,607556.0,601786.0,603936.0,611752.0,625530.0,635415.0,636710.0,...,4.2,3.4,2.9,2.2,2.4,2.5,11.7,6.0,3.5,NaN
12,IA,Iowa,1594400.0,1610634.0,1629047.0,1607931.0,1607438.0,1628510.0,1655924.0,1662155.0,...,4.2,3.7,3.6,3.1,2.6,2.7,5.2,3.8,2.7,NaN
13,ID,Idaho,661066.0,678281.0,685650.0,691702.0,702872.0,730354.0,744475.0,755287.0,...,4.4,3.9,3.7,3.2,2.9,2.9,5.5,3.5,2.7,NaN
14,IL,Illinois,6494429.0,6454092.0,6341891.0,6310520.0,6348716.0,6410767.0,6515687.0,6639198.0,...,7.2,6.0,5.9,4.9,4.4,4.0,9.3,6.1,4.6,NaN
15,IN,Indiana,3125304.0,3143985.0,3161709.0,3178568.0,3165247.0,3202215.0,3235980.0,3202589.0,...,5.9,4.8,4.4,3.5,3.4,3.3,7.3,3.9,3.0,NaN
16,KS,Kansas,1402606.0,1398521.0,1419335.0,1441065.0,1458910.0,1458767.0,1467553.0,1485414.0,...,4.5,4.2,4.0,3.6,3.4,3.3,5.8,3.3,2.7,NaN
17,KY,Kentucky,1957400.0,1953834.0,1944682.0,1965881.0,1969935.0,1991726.0,2026144.0,2035493.0,...,6.4,5.2,5.0,4.8,4.2,4.1,6.5,4.4,3.9,NaN
18,LA,Louisiana,2026392.0,2027220.0,2013652.0,2024914.0,2030415.0,2078215.0,2001297.0,2026793.0,...,6.3,6.3,6.1,5.1,4.8,4.6,8.6,5.6,3.7,NaN
19,MA,Massachusetts,3340566.0,3386892.0,3436864.0,3418989.0,3400830.0,3385536.0,3411688.0,3433239.0,...,5.7,4.8,4.0,3.8,3.5,3.0,9.4,5.5,3.8,NaN
20,MD,Maryland,2801391.0,2836279.0,2872367.0,2881024.0,2885111.0,2931581.0,2984444.0,2989317.0,...,5.7,5.0,4.3,4.0,3.8,3.4,6.5,5.3,3.2,NaN
21,ME,Maine,677489.0,674958.0,678559.0,685165.0,685989.0,695280.0,700747.0,699753.0,...,5.6,4.4,3.8,3.4,3.2,2.9,5.1,4.6,3.0,NaN
22,MI,Michigan,5156695.0,5138844.0,5034722.0,5036119.0,5056148.0,5069602.0,5056734.0,4994841.0,...,7.2,5.4,5.0,4.6,4.2,4.1,10.0,5.8,4.2,NaN
23,MN,Minnesota,2799111.0,2847955.0,2873004.0,2893369.0,2893478.0,2880908.0,2889613.0,2898861.0,...,4.3,3.8,3.9,3.5,3.0,3.3,6.3,3.8,2.7,NaN
24,MO,Missouri,2971441.0,2987905.0,2981097.0,2983337.0,2995924.0,3011096.0,3036656.0,3058119.0,...,6.2,5.1,4.5,3.7,3.2,3.2,6.1,4.1,2.5,NaN
25,MS,Mississippi,1309882.0,1294733.0,1290793.0,1304578.0,1314982.0,1317407.0,1280618.0,1293338.0,...,7.6,6.5,5.9,5.2,4.9,5.5,8.0,5.5,3.9,NaN
26,MT,Montana,470069.0,465355.0,466408.0,470502.0,478226.0,485546.0,495166.0,505095.0,...,4.7,4.3,4.3,4.1,3.7,3.5,5.8,3.4,2.6,NaN
27,NC,North Carolina,4127465.0,4191959.0,4209274.0,4285401.0,4287954.0,4348830.0,4461103.0,4528594.0,...,6.1,5.7,5.1,4.5,4.0,3.9,7.2,4.9,3.7,NaN
28,ND,North Dakota,342761.0,342528.0,342463.0,347099.0,353652.0,356385.0,362712.0,367564.0,...,2.6,2.8,3.1,2.6,2.4,2.2,5.0,3.1,2.1,NaN
29,NE,Nebraska,938849.0,945374.0,952937.0,967039.0,973636.0,972759.0,971430.0,979043.0,...,3.3,3.0,3.1,3.0,2.9,3.1,4.3,2.7,2.3,NaN
30,NH,New Hampshire,685799.0,692029.0,700563.0,708938.0,715495.0,726101.0,732384.0,737928.0,...,4.3,3.4,2.9,2.8,2.6,2.6,6.7,3.4,2.5,NaN
31,NJ,New Jersey,4287640.0,4294366.0,4345273.0,4344387.0,4348048.0,4387304.0,4436646.0,4436092.0,...,6.7,5.7,4.9,4.5,4.0,3.5,9.4,6.6,3.7,NaN
32,NM,New Mexico,846150.0,855088.0,866850.0,880251.0,890462.0,906007.0,914467.0,920673.0,...,6.6,6.6,6.7,6.1,4.9,5.0,7.9,7.1,4.0,NaN
33,NV,Nevada,1070776.0,1113529.0,1134096.0,1150376.0,1178651.0,1228449.0,1291512.0,1344209.0,...,8.2,6.8,5.8,5.0,4.4,4.1,13.5,6.9,5.4,NaN
34,NY,New York,9140541.0,9126538.0,9294770.0,9283810.0,9359930.0,9455488.0,9520386.0,9511023.0,...,6.3,5.2,4.9,4.6,4.1,3.9,9.8,7.0,4.3,NaN
35,OH,Ohio,5781442.0,5821151.0,5827493.0,5862996.0,5853714.0,5880691.0,5957220.0,6017203.0,...,5.8,5.0,5.0,5.0,4.5,4.2,8.2,5.1,4.0,NaN
36,OK,Oklahoma,1655517.0,1672620.0,1685334.0,1686378.0,1690505.0,1709289.0,1714440.0,1723271.0,...,4.3,4.3,4.6,4.0,3.3,3.1,6.3,4.0,3.0,NaN
37,OR,Oregon,1811837.0,1815076.0,1834254.0,1846328.0,1845407.0,1848897.0,1881770.0,1910890.0,...,6.7,5.5,4.7,4.1,4.0,3.7,7.6,5.2,4.2,NaN
38,PA,Pennsylvania,6105742.0,6178900.0,6214539.0,6157935.0,6212828.0,6256642.0,6297964.0,6346588.0,...,5.9,5.4,5.3,5.0,4.4,4.3,8.9,6.0,4.4,NaN
39,PR,Puerto Rico,1291993.0,1273405.0,1321370.0,1345782.0,1347047.0,1378062.0,1419874.0,1387359.0,...,13.9,12.0,11.8,10.8,9.2,8.3,NaN,7.9,6.0,NaN
40,RI,Rhode Island,542514.0,541661.0,550244.0,560785.0,555679.0,563439.0,571586.0,571086.0,...,7.8,6.0,5.2,4.5,4.0,3.5,9.2,5.5,3.2,NaN
41,SC,South Carolina,1965481.0,1941956.0,1954548.0,1999485.0,2043864.0,2071111.0,2148698.0,2155198.0,...,6.3,5.9,4.9,4.2,3.4,2.8,6.0,3.9,3.2,NaN
42,SD,South Dakota,408496.0,413493.0,416793.0,421524.0,425953.0,429361.0,432760.0,436295.0,...,3.3,3.0,3.0,3.1,2.8,2.8,4.2,2.6,2.1,NaN
43,TN,Tennessee,2849026.0,2857659.0,2898948.0,2904566.0,2897792.0,2898490.0,3014749.0,3043258.0,...,6.6,5.6,4.7,3.7,3.5,3.3,7.5,4.5,3.4,NaN
44,TX,Texas,10388337.0,10539140.0,10742014.0,10910636.0,10998258.0,11172694.0,11335112.0,11441054.0,...,5.2,4.5,4.6,4.3,3.9,3.5,7.7,5.6,3.9,NaN
45,US,United States,142601576.0,143786537.0,144839298.0,145660094.0,146724795.0,148597241.0,150707773.0,152191050.0,...,6.2,5.3,4.9,4.4,3.9,3.7,8.1,5.4,3.7,NaN
46,UT,Utah,1142860.0,1162874.0,1179433.0,1197252.0,1231740.0,1280653.0,1333278.0,1377638.0,...,3.6,3.5,3.3,3.1,2.9,2.5,4.8,2.7,2.3,NaN
47,VA,Virginia,3606390.0,3681107.0,3739499.0,3772549.0,3814529.0,3906549.0,3976503.0,4039414.0,...,5.1,4.4,4.0,3.7,3.0,2.8,6.5,3.9,2.9,NaN
48,VT,Vermont,334055.0,338145.0,343261.0,346380.0,347352.0,349521.0,355394.0,353268.0,...,4.0,3.5,3.1,3.0,2.5,2.1,5.7,3.7,2.6,NaN
49,WA,Washington,3087680.0,3085655.0,3101001.0,3136253.0,3189389.0,3259772.0,3330058.0,3401404.0,...,5.9,5.4,5.2,4.6,4.4,4.2,8.5,5.2,4.2,NaN
50,WI,Wisconsin,2985643.0,3017681.0,3016760.0,3045298.0,3034621.0,3029662.0,3066266.0,3087598.0,...,5.3,4.4,3.9,3.3,3.0,3.2,6.4,3.8,2.9,NaN
51,WV,West Virginia,799081.0,796596.0,798709.0,791841.0,789527.0,794557.0,804910.0,804305.0,...,6.5,6.6,6.1,5.2,5.1,5.0,8.2,5.1,3.9,NaN
52,WY,Wyoming,265701.0,268393.0,269405.0,272804.0,274736.0,279083.0,284826.0,290748.0,...,4.3,4.2,5.4,4.3,4.1,3.7,5.9,4.6,3.6,NaN

To ensure the new, pivoted dataset is clean and readable, we will perform a small sub-step here:

The Area_Name column now just represents state, so we can rename it accordingly.

In [15]:
# Rename the `Area_Name` column
dataset_pivoted = dataset_pivoted.rename(columns={'Area_Name': 'State (long)'})

# Display list of updated columns
list(dataset_pivoted.columns.values)

['State',
 'State (long)',
 'Civilian labor force (2000)',
 'Civilian labor force (2001)',
 'Civilian labor force (2002)',
 'Civilian labor force (2003)',
 'Civilian labor force (2004)',
 'Civilian labor force (2005)',
 'Civilian labor force (2006)',
 'Civilian labor force (2007)',
 'Civilian labor force (2008)',
 'Civilian labor force (2009)',
 'Civilian labor force (2010)',
 'Civilian labor force (2011)',
 'Civilian labor force (2012)',
 'Civilian labor force (2013)',
 'Civilian labor force (2014)',
 'Civilian labor force (2015)',
 'Civilian labor force (2016)',
 'Civilian labor force (2017)',
 'Civilian labor force (2018)',
 'Civilian labor force (2019)',
 'Civilian labor force (2020)',
 'Civilian labor force (2021)',
 'Civilian labor force (2022)',
 'Employed (2000)',
 'Employed (2001)',
 'Employed (2002)',
 'Employed (2003)',
 'Employed (2004)',
 'Employed (2005)',
 'Employed (2006)',
 'Employed (2007)',
 'Employed (2008)',
 'Employed (2009)',
 'Employed (2010)',
 'Employed (2011)',
 'Employed (2012)',
 'Employed (2013)',
 'Employed (2014)',
 'Employed (2015)',
 'Employed (2016)',
 'Employed (2017)',
 'Employed (2018)',
 'Employed (2019)',
 'Employed (2020)',
 'Employed (2021)',
 'Employed (2022)',
 'Med HH Income Percent of State Total (2021)',
 'Median Household Income (2021)',
 'Metro (2013)',
 'Rural Urban Continuum Code (2013)',
 'Unemployed (2000)',
 'Unemployed (2001)',
 'Unemployed (2002)',
 'Unemployed (2003)',
 'Unemployed (2004)',
 'Unemployed (2005)',
 'Unemployed (2006)',
 'Unemployed (2007)',
 'Unemployed (2008)',
 'Unemployed (2009)',
 'Unemployed (2010)',
 'Unemployed (2011)',
 'Unemployed (2012)',
 'Unemployed (2013)',
 'Unemployed (2014)',
 'Unemployed (2015)',
 'Unemployed (2016)',
 'Unemployed (2017)',
 'Unemployed (2018)',
 'Unemployed (2019)',
 'Unemployed (2020)',
 'Unemployed (2021)',
 'Unemployed (2022)',
 'Unemployment rate (2000)',
 'Unemployment rate (2001)',
 'Unemployment rate (2002)',
 'Unemployment rate (2003)',
 'Unemployment rate (2004)',
 'Unemployment rate (2005)',
 'Unemployment rate (2006)',
 'Unemployment rate (2007)',
 'Unemployment rate (2008)',
 'Unemployment rate (2009)',
 'Unemployment rate (2010)',
 'Unemployment rate (2011)',
 'Unemployment rate (2012)',
 'Unemployment rate (2013)',
 'Unemployment rate (2014)',
 'Unemployment rate (2015)',
 'Unemployment rate (2016)',
 'Unemployment rate (2017)',
 'Unemployment rate (2018)',
 'Unemployment rate (2019)',
 'Unemployment rate (2020)',
 'Unemployment rate (2021)',
 'Unemployment rate (2022)',
 'Urban Influence Code (2013)']

In [16]:
# Count number of rows in the pivoted dataset
len(dataset_pivoted)

53

Final preview of the cleaned dataset:

In [17]:
dataset_pivoted

Attribute,State,State (long),Civilian labor force (2000),Civilian labor force (2001),Civilian labor force (2002),Civilian labor force (2003),Civilian labor force (2004),Civilian labor force (2005),Civilian labor force (2006),Civilian labor force (2007),...,Unemployment rate (2014),Unemployment rate (2015),Unemployment rate (2016),Unemployment rate (2017),Unemployment rate (2018),Unemployment rate (2019),Unemployment rate (2020),Unemployment rate (2021),Unemployment rate (2022),Urban Influence Code (2013)
0,AK,Alaska,319777.0,321652.0,327054.0,332494.0,337469.0,344157.0,348756.0,350233.0,...,6.7,6.3,6.6,6.5,6.0,5.6,8.3,6.4,4.0,NaN
1,AL,Alabama,2147173.0,2128027.0,2112621.0,2128668.0,2138306.0,2140356.0,2170007.0,2180448.0,...,6.7,6.1,5.9,4.5,3.9,3.2,6.4,3.4,2.6,NaN
2,AR,Arkansas,1260507.0,1261419.0,1276964.0,1282578.0,1302378.0,1333880.0,1346532.0,1350811.0,...,5.9,5.0,4.0,3.7,3.7,3.5,6.2,4.1,3.3,NaN
3,AZ,Arizona,2510611.0,2593664.0,2683502.0,2728649.0,2788618.0,2862517.0,2970679.0,3018805.0,...,6.8,6.1,5.5,5.0,4.8,4.8,7.8,5.1,3.8,NaN
4,CA,California,16837536.0,17096428.0,17246528.0,17271899.0,17374506.0,17537931.0,17661179.0,17910726.0,...,7.6,6.3,5.5,4.8,4.2,4.1,10.1,7.3,4.2,NaN
5,CO,Colorado,2358371.0,2396012.0,2448903.0,2490397.0,2539389.0,2572382.0,2640452.0,2687742.0,...,5.0,3.7,3.1,2.6,3.0,2.7,6.8,5.4,3.0,NaN
6,CT,Connecticut,1760697.0,1749195.0,1776064.0,1785737.0,1777510.0,1794301.0,1831083.0,1856008.0,...,6.6,5.6,4.8,4.4,3.9,3.6,7.9,6.3,4.2,NaN
7,DC,District of Columbia,309977.0,311232.0,308760.0,308454.0,313735.0,318130.0,320581.0,326557.0,...,7.7,6.9,6.2,6.1,5.7,5.5,7.9,6.8,4.7,1.0
8,DE,Delaware,412956.0,421563.0,417207.0,415890.0,421093.0,433375.0,443228.0,445306.0,...,5.6,4.8,4.5,4.5,3.7,3.6,7.5,5.5,4.5,NaN
9,FL,Florida,7917857.0,8048882.0,8050051.0,8123135.0,8347316.0,8647279.0,8927098.0,9113604.0,...,6.4,5.5,4.9,4.3,3.6,3.2,8.1,4.6,2.9,NaN
10,GA,Georgia,4202695.0,4257901.0,4341617.0,4414282.0,4464780.0,4598159.0,4713863.0,4810264.0,...,7.1,6.1,5.4,4.8,4.0,3.6,6.5,3.9,3.0,NaN
11,HI,Hawaii,605395.0,607556.0,601786.0,603936.0,611752.0,625530.0,635415.0,636710.0,...,4.2,3.4,2.9,2.2,2.4,2.5,11.7,6.0,3.5,NaN
12,IA,Iowa,1594400.0,1610634.0,1629047.0,1607931.0,1607438.0,1628510.0,1655924.0,1662155.0,...,4.2,3.7,3.6,3.1,2.6,2.7,5.2,3.8,2.7,NaN
13,ID,Idaho,661066.0,678281.0,685650.0,691702.0,702872.0,730354.0,744475.0,755287.0,...,4.4,3.9,3.7,3.2,2.9,2.9,5.5,3.5,2.7,NaN
14,IL,Illinois,6494429.0,6454092.0,6341891.0,6310520.0,6348716.0,6410767.0,6515687.0,6639198.0,...,7.2,6.0,5.9,4.9,4.4,4.0,9.3,6.1,4.6,NaN
15,IN,Indiana,3125304.0,3143985.0,3161709.0,3178568.0,3165247.0,3202215.0,3235980.0,3202589.0,...,5.9,4.8,4.4,3.5,3.4,3.3,7.3,3.9,3.0,NaN
16,KS,Kansas,1402606.0,1398521.0,1419335.0,1441065.0,1458910.0,1458767.0,1467553.0,1485414.0,...,4.5,4.2,4.0,3.6,3.4,3.3,5.8,3.3,2.7,NaN
17,KY,Kentucky,1957400.0,1953834.0,1944682.0,1965881.0,1969935.0,1991726.0,2026144.0,2035493.0,...,6.4,5.2,5.0,4.8,4.2,4.1,6.5,4.4,3.9,NaN
18,LA,Louisiana,2026392.0,2027220.0,2013652.0,2024914.0,2030415.0,2078215.0,2001297.0,2026793.0,...,6.3,6.3,6.1,5.1,4.8,4.6,8.6,5.6,3.7,NaN
19,MA,Massachusetts,3340566.0,3386892.0,3436864.0,3418989.0,3400830.0,3385536.0,3411688.0,3433239.0,...,5.7,4.8,4.0,3.8,3.5,3.0,9.4,5.5,3.8,NaN
20,MD,Maryland,2801391.0,2836279.0,2872367.0,2881024.0,2885111.0,2931581.0,2984444.0,2989317.0,...,5.7,5.0,4.3,4.0,3.8,3.4,6.5,5.3,3.2,NaN
21,ME,Maine,677489.0,674958.0,678559.0,685165.0,685989.0,695280.0,700747.0,699753.0,...,5.6,4.4,3.8,3.4,3.2,2.9,5.1,4.6,3.0,NaN
22,MI,Michigan,5156695.0,5138844.0,5034722.0,5036119.0,5056148.0,5069602.0,5056734.0,4994841.0,...,7.2,5.4,5.0,4.6,4.2,4.1,10.0,5.8,4.2,NaN
23,MN,Minnesota,2799111.0,2847955.0,2873004.0,2893369.0,2893478.0,2880908.0,2889613.0,2898861.0,...,4.3,3.8,3.9,3.5,3.0,3.3,6.3,3.8,2.7,NaN
24,MO,Missouri,2971441.0,2987905.0,2981097.0,2983337.0,2995924.0,3011096.0,3036656.0,3058119.0,...,6.2,5.1,4.5,3.7,3.2,3.2,6.1,4.1,2.5,NaN
25,MS,Mississippi,1309882.0,1294733.0,1290793.0,1304578.0,1314982.0,1317407.0,1280618.0,1293338.0,...,7.6,6.5,5.9,5.2,4.9,5.5,8.0,5.5,3.9,NaN
26,MT,Montana,470069.0,465355.0,466408.0,470502.0,478226.0,485546.0,495166.0,505095.0,...,4.7,4.3,4.3,4.1,3.7,3.5,5.8,3.4,2.6,NaN
27,NC,North Carolina,4127465.0,4191959.0,4209274.0,4285401.0,4287954.0,4348830.0,4461103.0,4528594.0,...,6.1,5.7,5.1,4.5,4.0,3.9,7.2,4.9,3.7,NaN
28,ND,North Dakota,342761.0,342528.0,342463.0,347099.0,353652.0,356385.0,362712.0,367564.0,...,2.6,2.8,3.1,2.6,2.4,2.2,5.0,3.1,2.1,NaN
29,NE,Nebraska,938849.0,945374.0,952937.0,967039.0,973636.0,972759.0,971430.0,979043.0,...,3.3,3.0,3.1,3.0,2.9,3.1,4.3,2.7,2.3,NaN
30,NH,New Hampshire,685799.0,692029.0,700563.0,708938.0,715495.0,726101.0,732384.0,737928.0,...,4.3,3.4,2.9,2.8,2.6,2.6,6.7,3.4,2.5,NaN
31,NJ,New Jersey,4287640.0,4294366.0,4345273.0,4344387.0,4348048.0,4387304.0,4436646.0,4436092.0,...,6.7,5.7,4.9,4.5,4.0,3.5,9.4,6.6,3.7,NaN
32,NM,New Mexico,846150.0,855088.0,866850.0,880251.0,890462.0,906007.0,914467.0,920673.0,...,6.6,6.6,6.7,6.1,4.9,5.0,7.9,7.1,4.0,NaN
33,NV,Nevada,1070776.0,1113529.0,1134096.0,1150376.0,1178651.0,1228449.0,1291512.0,1344209.0,...,8.2,6.8,5.8,5.0,4.4,4.1,13.5,6.9,5.4,NaN
34,NY,New York,9140541.0,9126538.0,9294770.0,9283810.0,9359930.0,9455488.0,9520386.0,9511023.0,...,6.3,5.2,4.9,4.6,4.1,3.9,9.8,7.0,4.3,NaN
35,OH,Ohio,5781442.0,5821151.0,5827493.0,5862996.0,5853714.0,5880691.0,5957220.0,6017203.0,...,5.8,5.0,5.0,5.0,4.5,4.2,8.2,5.1,4.0,NaN
36,OK,Oklahoma,1655517.0,1672620.0,1685334.0,1686378.0,1690505.0,1709289.0,1714440.0,1723271.0,...,4.3,4.3,4.6,4.0,3.3,3.1,6.3,4.0,3.0,NaN
37,OR,Oregon,1811837.0,1815076.0,1834254.0,1846328.0,1845407.0,1848897.0,1881770.0,1910890.0,...,6.7,5.5,4.7,4.1,4.0,3.7,7.6,5.2,4.2,NaN
38,PA,Pennsylvania,6105742.0,6178900.0,6214539.0,6157935.0,6212828.0,6256642.0,6297964.0,6346588.0,...,5.9,5.4,5.3,5.0,4.4,4.3,8.9,6.0,4.4,NaN
39,PR,Puerto Rico,1291993.0,1273405.0,1321370.0,1345782.0,1347047.0,1378062.0,1419874.0,1387359.0,...,13.9,12.0,11.8,10.8,9.2,8.3,NaN,7.9,6.0,NaN
40,RI,Rhode Island,542514.0,541661.0,550244.0,560785.0,555679.0,563439.0,571586.0,571086.0,...,7.8,6.0,5.2,4.5,4.0,3.5,9.2,5.5,3.2,NaN
41,SC,South Carolina,1965481.0,1941956.0,1954548.0,1999485.0,2043864.0,2071111.0,2148698.0,2155198.0,...,6.3,5.9,4.9,4.2,3.4,2.8,6.0,3.9,3.2,NaN
42,SD,South Dakota,408496.0,413493.0,416793.0,421524.0,425953.0,429361.0,432760.0,436295.0,...,3.3,3.0,3.0,3.1,2.8,2.8,4.2,2.6,2.1,NaN
43,TN,Tennessee,2849026.0,2857659.0,2898948.0,2904566.0,2897792.0,2898490.0,3014749.0,3043258.0,...,6.6,5.6,4.7,3.7,3.5,3.3,7.5,4.5,3.4,NaN
44,TX,Texas,10388337.0,10539140.0,10742014.0,10910636.0,10998258.0,11172694.0,11335112.0,11441054.0,...,5.2,4.5,4.6,4.3,3.9,3.5,7.7,5.6,3.9,NaN
45,US,United States,142601576.0,143786537.0,144839298.0,145660094.0,146724795.0,148597241.0,150707773.0,152191050.0,...,6.2,5.3,4.9,4.4,3.9,3.7,8.1,5.4,3.7,NaN
46,UT,Utah,1142860.0,1162874.0,1179433.0,1197252.0,1231740.0,1280653.0,1333278.0,1377638.0,...,3.6,3.5,3.3,3.1,2.9,2.5,4.8,2.7,2.3,NaN
47,VA,Virginia,3606390.0,3681107.0,3739499.0,3772549.0,3814529.0,3906549.0,3976503.0,4039414.0,...,5.1,4.4,4.0,3.7,3.0,2.8,6.5,3.9,2.9,NaN
48,VT,Vermont,334055.0,338145.0,343261.0,346380.0,347352.0,349521.0,355394.0,353268.0,...,4.0,3.5,3.1,3.0,2.5,2.1,5.7,3.7,2.6,NaN
49,WA,Washington,3087680.0,3085655.0,3101001.0,3136253.0,3189389.0,3259772.0,3330058.0,3401404.0,...,5.9,5.4,5.2,4.6,4.4,4.2,8.5,5.2,4.2,NaN
50,WI,Wisconsin,2985643.0,3017681.0,3016760.0,3045298.0,3034621.0,3029662.0,3066266.0,3087598.0,...,5.3,4.4,3.9,3.3,3.0,3.2,6.4,3.8,2.9,NaN
51,WV,West Virginia,799081.0,796596.0,798709.0,791841.0,789527.0,794557.0,804910.0,804305.0,...,6.5,6.6,6.1,5.2,5.1,5.0,8.2,5.1,3.9,NaN
52,WY,Wyoming,265701.0,268393.0,269405.0,272804.0,274736.0,279083.0,284826.0,290748.0,...,4.3,4.2,5.4,4.3,4.1,3.7,5.9,4.6,3.6,NaN

We now have a clean, pivoted dataset to work with.

## Conclusion

The transformations in this notebook included:

1. Dropping county-level data to focus on state-level insights
2. Removing columns deemed unnecessary
3. Refining statistic/attribute labels for clarity
4. Eliminating duplicate entries
5. Pivoting the dataset into a wide format for easier analysis

The dataset comes from the United States Department of Agriculture's (USDA) Economic Research Service. Since it is completely free and public domain, it is not subject to much regulation. However, it should still be utilized and presented honestly and with good will. By dropping county-specific data, we lost granularity, which can lead to overlooking local nuances and misrepresenting regional differences. I assumed that the dataset did not contain any bad data, since it was government-sourced, but practically I should check for missing values, abnormal outliers, and values of incorrect or unexpected types. The data was obtained legally via download from the USDA's public website here: https://www.ers.usda.gov/data-products/county-level-data-sets/county-level-data-sets-download-data

In order to mitigate the risk of reduced granularity from my removal of county-level data, I plan to be transparent about performing that transformation. If appropriate, I may even write a disclaimer warning users of my prepared data from over-generalizing, and to keep in mind that state and national-level data misses many nuances of specific cities, towns, and sub-regions.

In [18]:
import pandas as pd
import numpy as np

# Save to parquet
dataset_pivoted.to_parquet('labor_force_data.parquet')

# Read it back
df_loaded = pd.read_parquet('labor_force_data.parquet')

# Compare the two DataFrames
def verify_dataframes(original, loaded):
    # Check if shapes match
    if original.shape != loaded.shape:
        print(f"Shape mismatch: Original {original.shape} vs Loaded {loaded.shape}")
        return False
        
    # Check column names and order
    if not original.columns.equals(loaded.columns):
        print("Column names or order don't match")
        print("Missing in loaded:", set(original.columns) - set(loaded.columns))
        print("Extra in loaded:", set(loaded.columns) - set(original.columns))
        return False
    
    # Check dtypes
    if not original.dtypes.equals(loaded.dtypes):
        print("Data types don't match")
        dtype_diff = pd.DataFrame({
            'original': original.dtypes,
            'loaded': loaded.dtypes
        }).loc[original.dtypes != loaded.dtypes]
        print(dtype_diff)
        
    # Check actual data values
    is_equal = original.equals(loaded)
    if not is_equal:
        # Find differences if not equal
        # For numeric columns, find where absolute difference exceeds a small threshold
        for col in original.select_dtypes(include=np.number).columns:
            mask = ~(original[col].fillna(0) - loaded[col].fillna(0)).abs().lt(1e-10)
            if mask.any():
                diff_indices = mask[mask].index
                print(f"Differences in column '{col}' at indices: {diff_indices.tolist()}")
                print("Sample differences:")
                for idx in diff_indices[:5]:  # Show first 5 differences
                    print(f"  Index {idx}: Original={original.loc[idx, col]}, Loaded={loaded.loc[idx, col]}")
        
        # For non-numeric columns, find direct mismatches
        for col in original.select_dtypes(exclude=np.number).columns:
            mask = original[col] != loaded[col]
            if mask.any():
                diff_indices = mask[mask].index
                print(f"Differences in column '{col}' at indices: {diff_indices.tolist()}")
                print("Sample differences:")
                for idx in diff_indices[:5]:  # Show first 5 differences
                    print(f"  Index {idx}: Original={original.loc[idx, col]}, Loaded={loaded.loc[idx, col]}")
    
    return is_equal

# Run the verification
is_identical = verify_dataframes(dataset_pivoted, df_loaded)
print("Verification result:", "Success - DataFrames are identical" if is_identical else "Failed - DataFrames differ")

Verification result: Success - DataFrames are identical

In [27]:
if dataset_pivoted.equals(df_loaded):
    print("Verification passed - DataFrames are identical")
else:
    print("Verification failed - DataFrames differ")

Verification passed - DataFrames are identical

In [19]:
dataset_pivoted.head()

Attribute,State,State (long),Civilian labor force (2000),Civilian labor force (2001),Civilian labor force (2002),Civilian labor force (2003),Civilian labor force (2004),Civilian labor force (2005),Civilian labor force (2006),Civilian labor force (2007),...,Unemployment rate (2014),Unemployment rate (2015),Unemployment rate (2016),Unemployment rate (2017),Unemployment rate (2018),Unemployment rate (2019),Unemployment rate (2020),Unemployment rate (2021),Unemployment rate (2022),Urban Influence Code (2013)
0,AK,Alaska,319777.0,321652.0,327054.0,332494.0,337469.0,344157.0,348756.0,350233.0,...,6.7,6.3,6.6,6.5,6.0,5.6,8.3,6.4,4.0,NaN
1,AL,Alabama,2147173.0,2128027.0,2112621.0,2128668.0,2138306.0,2140356.0,2170007.0,2180448.0,...,6.7,6.1,5.9,4.5,3.9,3.2,6.4,3.4,2.6,NaN
2,AR,Arkansas,1260507.0,1261419.0,1276964.0,1282578.0,1302378.0,1333880.0,1346532.0,1350811.0,...,5.9,5.0,4.0,3.7,3.7,3.5,6.2,4.1,3.3,NaN
3,AZ,Arizona,2510611.0,2593664.0,2683502.0,2728649.0,2788618.0,2862517.0,2970679.0,3018805.0,...,6.8,6.1,5.5,5.0,4.8,4.8,7.8,5.1,3.8,NaN
4,CA,California,16837536.0,17096428.0,17246528.0,17271899.0,17374506.0,17537931.0,17661179.0,17910726.0,...,7.6,6.3,5.5,4.8,4.2,4.1,10.1,7.3,4.2,NaN

In [20]:
# Save the pivoted dataset to a CSV file
output_csv_path = 'USDA_dataset_1.csv'
dataset_pivoted.to_csv(output_csv_path, index=False)
print(f"Dataset successfully saved to {output_csv_path}")

# Verify the file was created
import os
if os.path.exists(output_csv_path):
    print(f"File size: {os.path.getsize(output_csv_path) / (1024*1024):.2f} MB")
    # Display the first few rows of the saved file to verify
    df_verification = pd.read_csv(output_csv_path, nrows=5)
    print("\nPreview of saved CSV file:")
    print(df_verification.head())
else:
    print("Error: File was not created successfully")

Dataset successfully saved to USDA_dataset_1.csv
File size: 0.04 MB

Preview of saved CSV file:
  State State (long)  Civilian labor force (2000)  \
0    AK       Alaska                     319777.0
1    AL      Alabama                    2147173.0
2    AR     Arkansas                    1260507.0
3    AZ      Arizona                    2510611.0
4    CA   California                   16837536.0

   Civilian labor force (2001)  Civilian labor force (2002)  \
0                     321652.0                     327054.0
1                    2128027.0                    2112621.0
2                    1261419.0                    1276964.0
3                    2593664.0                    2683502.0
4                   17096428.0                   17246528.0

   Civilian labor force (2003)  Civilian labor force (2004)  \
0                     332494.0                     337469.0
1                    2128668.0                    2138306.0
2                    1282578.0                    1302378.0
3                    2728649.0                    2788618.0
4                   17271899.0                   17374506.0

   Civilian labor force (2005)  Civilian labor force (2006)  \
0                     344157.0                     348756.0
1                    2140356.0                    2170007.0
2                    1333880.0                    1346532.0
3                    2862517.0                    2970679.0
4                   17537931.0                   17661179.0

   Civilian labor force (2007)  ...  Unemployment rate (2014)  \
0                     350233.0  ...                       6.7
1                    2180448.0  ...                       6.7
2                    1350811.0  ...                       5.9
3                    3018805.0  ...                       6.8
4                   17910726.0  ...                       7.6

   Unemployment rate (2015)  Unemployment rate (2016)  \
0                       6.3                       6.6
1                       6.1                       5.9
2                       5.0                       4.0
3                       6.1                       5.5
4                       6.3                       5.5

   Unemployment rate (2017)  Unemployment rate (2018)  \
0                       6.5                       6.0
1                       4.5                       3.9
2                       3.7                       3.7
3                       5.0                       4.8
4                       4.8                       4.2

   Unemployment rate (2019)  Unemployment rate (2020)  \
0                       5.6                       8.3
1                       3.2                       6.4
2                       3.5                       6.2
3                       4.8                       7.8
4                       4.1                      10.1

   Unemployment rate (2021)  Unemployment rate (2022)  \
0                       6.4                       4.0
1                       3.4                       2.6
2                       4.1                       3.3
3                       5.1                       3.8
4                       7.3                       4.2

   Urban Influence Code (2013)
0                          NaN
1                          NaN
2                          NaN
3                          NaN
4                          NaN

[5 rows x 99 columns]